### PR TITLE
Micropython update

### PR DESCRIPTION
**Pull request by amirgon**
@kisvegabor The main things we discussed are implemented here:
- structs support, including colors structs, styles, themes, global fonts, etc.
- gc support
- Symbols support
- Added example. This is actually @rreilink's advanced example which I ported to Micropython. There are still many differences between the Python and Micropython syntax (unfortunately), but it does the same thing.
- The Makefile now runs `gen_mpy.py`, generates the bindings and builds them automatically. The commited `lv_mpy.c` remains **as an example**, it is not part of the build and doesn't have to be aligned with `lv_conf.h`. The actual generated `lv_mpy.c` is generated under `build` directory.

Still open issues:
- There is no naming convention to identify "private" functions or structs. So all functions are bound, including many I assume the user should not be exposed to (such as `ll_...` functions). I suggest adding a single underscore to any "private" function or struct.
- I don't handle arrays yet (to allow using functions such as `lv_line_set_points` or updating structs such as `lv_chart_series_t`). I'll add this in the future, I plan to allow the user pass a native python list and convert it automatically, but I still need to think about it.
- Macros are not handled. Except from Symbols which I implemented, we still need to handle color macros. I suggest adding inline functions in addition to macros, both functions for converting colors and functions for the colors themselves. Something like `static inline lv_color_t lv_get_color(int color_id)`. The advantage of using inline functions is that the compiler optimizes them down to a constant when possible, so they cost same as using the color macros directly (same in program-memory, data-ram and performance terms)
- It's not really tested, except from some very simple examples. I guess there are multiple issues that are still to be discovered, I hope to get inputs from users once this goes to a formal release.

So - in order to release this on the `v5.3`, what do you need? Should I merge the changes to `v5.3` branch and send you a PR to lvgl repo?

### CODE REVIEW

**Comment by embeddedt** [comment]
@amirgon I think you should rename the sample `lv_mpy.c` to `lv_mpy_example.c`. Otherwise a user may become confused and think that they can modify that `lv_mpy.c` to do what they want.

**Comment by amirgon** [comment]
@embeddedt Renamed.
@kisvegabor I made some changes in lv_colors.h to expose `OPA` macros and `LV_COLOR_HEX` macros to Micropython.

**Comment by kisvegabor** [comment]
Thank you for the update.

> There is no naming convention to identify "private" functions or structs. So all functions are bound, including many I assume the user should not be exposed to (such as ll_... functions). I suggest adding a single underscore to any "private" function or struct.

It's quite reasonable, great idea! 

> I don't handle arrays yet (to allow using functions such as lv_line_set_points or updating structs such as lv_chart_series_t). I'll add this in the future, I plan to allow the user pass a native python list and convert it automatically, but I still need to think about it.

No problem, it's still an experimental version.

> It's not really tested, except from some very simple examples. I guess there are multiple issues that are still to be discovered, I hope to get inputs from users once this goes to a formal release.

Yes, we will see. After the release let"s open a an issue for `Micropython binding feedback`.

> So - in order to release this on the v5.3, what do you need? Should I merge the changes to v5.3 branch and send you a PR to lvgl repo?

Yes, please!

**Comment by amirgon** [comment]
> It's quite reasonable, great idea!

@kisvegabor I would like to rename private functions/structs, but I'm not sure which should really be private (never allow user access) and which should still be available for the user in some cases.  
Could you help listing the private functions/structs? If you do I'll rename them (underscore prefix) in my PR.

**Comment by kisvegabor** [comment]
Basically, everything in the header files is public. As I see now only the global símbols (things form the header files) are added to the binding. 

Before renaming let's merge the current version to see these updates in action.  In addition, the renaming might cause conflicts so better to have a "stabe base".

**Pull request merged**
